"""Tests for the feedback loop — labels expired signals with actual_move."""

from datetime import datetime, timedelta, timezone
from unittest.mock import patch

import pytest

from src.ingestion.feedback_loop import label_expired_signals
from src.ingestion.market_data import ReturnWindow
from src.models.signal import Signal, SignalType


def _signal(
    signal_id: str = "sig_test_1",
    ticker: str = "AAPL",
    impact_window: str = "24h",
    age_hours: float = 48.0,
    actual_move: float | None = None,
) -> Signal:
    """Build a Signal at a chosen age, defaulting to expired."""
    return Signal(
        signal_id=signal_id,
        event_id=f"evt_{signal_id}",
        timestamp=datetime.now(timezone.utc) - timedelta(hours=age_hours),
        ticker=ticker,
        signal_type=SignalType.WATCH,
        signal_text="Test signal for feedback loop unit tests",
        confidence=0.72,
        rationale="Synthetic signal generated by feedback-loop unit tests; no real market data was used to construct this rationale.",
        uncertainty="Test signal — outcome unknown until market data is fetched.",
        impact_window=impact_window,
        predicted_move=0.025,
        actual_move=actual_move,
        evidence=[],
        citations=[],
    )


@pytest.mark.asyncio
async def test_no_expired_signals_returns_zeros():
    with patch(
        "src.ingestion.feedback_loop.list_unlabeled_expired",
        return_value=[],
    ):
        stats = await label_expired_signals()
    assert stats == {"scanned": 0, "labeled": 0, "no_data": 0, "errors": 0}


@pytest.mark.asyncio
async def test_labels_signal_when_market_data_returns_window():
    sig = _signal()
    return_window = ReturnWindow(
        window="24h", return_pct=0.0312, pre_price=180.0, post_price=185.6, volatility=0.018,
    )
    with patch(
        "src.ingestion.feedback_loop.list_unlabeled_expired",
        return_value=[sig],
    ), patch(
        "src.ingestion.feedback_loop.compute_post_event_returns",
        return_value=[return_window],
    ), patch(
        "src.ingestion.feedback_loop.update_actual_move",
        return_value=True,
    ) as mock_update:
        stats = await label_expired_signals()

    assert stats["scanned"] == 1
    assert stats["labeled"] == 1
    assert stats["no_data"] == 0
    mock_update.assert_called_once_with(sig.signal_id, 0.0312)


@pytest.mark.asyncio
async def test_no_data_when_market_data_returns_empty():
    sig = _signal()
    with patch(
        "src.ingestion.feedback_loop.list_unlabeled_expired",
        return_value=[sig],
    ), patch(
        "src.ingestion.feedback_loop.compute_post_event_returns",
        return_value=[],
    ), patch(
        "src.ingestion.feedback_loop.update_actual_move",
        return_value=True,
    ) as mock_update:
        stats = await label_expired_signals()

    assert stats["scanned"] == 1
    assert stats["labeled"] == 0
    assert stats["no_data"] == 1
    mock_update.assert_not_called()


@pytest.mark.asyncio
async def test_error_in_market_data_does_not_break_batch():
    sig_a = _signal(signal_id="sig_a", ticker="AAPL")
    sig_b = _signal(signal_id="sig_b", ticker="MSFT")
    rw_b = ReturnWindow(
        window="24h", return_pct=-0.012, pre_price=400.0, post_price=395.2, volatility=0.01,
    )

    async def fake_market(ticker, **kwargs):
        if ticker == "AAPL":
            raise RuntimeError("Alpha Vantage 429")
        return [rw_b]

    with patch(
        "src.ingestion.feedback_loop.list_unlabeled_expired",
        return_value=[sig_a, sig_b],
    ), patch(
        "src.ingestion.feedback_loop.compute_post_event_returns",
        side_effect=fake_market,
    ), patch(
        "src.ingestion.feedback_loop.update_actual_move",
        return_value=True,
    ) as mock_update:
        stats = await label_expired_signals()

    assert stats["scanned"] == 2
    assert stats["labeled"] == 1
    assert stats["errors"] == 1
    mock_update.assert_called_once_with("sig_b", -0.012)


@pytest.mark.asyncio
async def test_passes_signal_specific_window_to_market_data():
    sig = _signal(impact_window="1w")
    rw = ReturnWindow(
        window="1w", return_pct=0.05, pre_price=100.0, post_price=105.0, volatility=0.02,
    )
    captured: dict = {}

    async def fake_market(ticker, event_timestamp, windows=None):
        captured["windows"] = windows
        return [rw]

    with patch(
        "src.ingestion.feedback_loop.list_unlabeled_expired",
        return_value=[sig],
    ), patch(
        "src.ingestion.feedback_loop.compute_post_event_returns",
        side_effect=fake_market,
    ), patch(
        "src.ingestion.feedback_loop.update_actual_move",
        return_value=True,
    ):
        await label_expired_signals()

    assert captured["windows"] == ["1w"]
